server:
  port: 8080
  http2:
    enabled: true
  compression:
    enabled: true
  error:
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always
  max-http-header-size: 2MB
  shutdown: graceful
spring:
  application:
    name: alert
  jackson:
    default-property-inclusion: non_empty
    property-naming-strategy: SNAKE_CASE
    locale: id_ID
    time-zone: Asia/Jakarta
    date-format: dd/MM/yyyy
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  data:
    mongodb:
      database: alert
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      auto-index-creation: true
      uri: mongodb+srv://admin:admin@cluster0.nqrxeg9.mongodb.net/?retryWrites=true&w=majority
  webflux:
    format:
      date: dd/MM/yyyy
  mvc:
    format:
      date: dd/MM/yyyy
#debug: true
