server:
  port: 80
  http2:
    enabled: true
  compression:
    enabled: true
  error:
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always
  max-http-header-size: 2MB
  shutdown: graceful
spring:
  application:
    name: api
  security:
    user:
      name: admin
      password: admin
  jackson:
    default-property-inclusion: non_empty
    property-naming-strategy: SNAKE_CASE
    locale: id_ID
    time-zone: Asia/Jakarta
    date-format: dd/MM/yyyy
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  main:
    allow-circular-references: true
  data:
    mongodb:
      database: octagram
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      auto-index-creation: true
  webflux:
    format:
      date: dd/MM/yyyy
  mvc:
    format:
      date: dd/MM/yyyy
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,shutdown
debug: true
